# Matlab CircleCI 2.0 configuration file

version: 2.1

jobs:

  build:

    machine:
      image: 'ubuntu-1604:201903-01'

    working_directory: ~/boom

    steps:
      - checkout
      - matlab/install
      - run:
          name: Run Tests
          command: matlab -nodisplay -nosplash -nodesktop -r "run('src/+examplemoduletests/run.m');exit;"

      - store_artifacts:
          path: ./tmp
          destination: test-reports

orbs:
  matlab: mathworks/matlab@0.5.0
